### ISSUE TITLE
Upload sketch to arduino fails.

### ISSUE THREAD

**Issue by cbpdk** [DIYOSEPP/EspUnoWiFi#8]
Kubuntu 18.04
Arduino Ide 1.8.16
esp8266 sdk 3.02

Wemos NodeMCU 
Arduino Uno

I have compiled and installed EspUnoWifi onto Wemos NodeMCU and connected it to an Arduino Uno.

Uploading a sketch to the NodeMCU works fine and receiving data from the Arduino Uno also works.
But trying to upload a sketch to the Arduino using the network port and selecting board Arduino Wifi, fails with this message:
`
Sketch uses 8386 bytes (25%) of program storage space. Maximum is 32256 bytes.
Global variables use 639 bytes (31%) of dynamic memory, leaving 1409 bytes for local variables. Maximum is 2048 bytes.
java.io.IOException: Cannot run program "{tools.arduino_ota.cmd}": error=2, Ingen sådan fil eller filkatalog
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:11)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.GenericNetworkUploader.uploadUsingPreferences(GenericNetworkUploader.java:99)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2061)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, Ingen sådan fil eller filkatalog
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more
An error occurred while uploading the sketch
`
I cannot find the tools.arduino_ota.cmd, only ArduinoOTA.

**Comment by cbpdk** [comment]
The issue is solved. Removed the .arduino15 directory and just re-compiled the source and the upload worked as described.
Too many updates etc.
Thank you for the project.
